"""dropping co2_emission_rate column from power_plant table

Revision ID: 10806a54a5b7
Revises: 84cedb1b7a5e
Create Date: 2024-04-04 14:47:37.118555

"""

# revision identifiers, used by Alembic.
revision = '10806a54a5b7'
down_revision = '84cedb1b7a5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('power_plant', 'co2_emission_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_plant', sa.Column('co2_emission_rate', sa.DOUBLE_PRECISION(precision=53),
                                           autoincrement=False, nullable=True))
    # ### end Alembic commands ###
