"""Create first model

Revision ID: 84cedb1b7a5e
Revises: None
Create Date: 2024-03-22 13:55:52.705074

"""

# revision identifiers, used by Alembic.
revision = '84cedb1b7a5e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_source_name', sa.String(), nullable=False),
    sa.Column('data_source_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_plant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('power_plant_name', sa.String(), nullable=False),
    sa.Column('power_plant_type', sa.String(), nullable=False),
    sa.Column('co2_emission_rate', sa.Float(), nullable=True),
    sa.Column('power_status', sa.String(), nullable=False),
    sa.Column('renewable_status', sa.String(), nullable=False),
    sa.Column('carbon_source_rating', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emission_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emission_type', sa.String(), nullable=False),
    sa.Column('emission_amount', sa.Float(), nullable=False),
    sa.Column('calculation_method', sa.String(), nullable=True),
    sa.Column('data_estimation', sa.Boolean(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('power_plant_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['power_plant_id'], ['power_plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('power_plant_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['power_plant_id'], ['power_plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('power')
    op.drop_table('emission_data')
    op.drop_table('power_plant')
    op.drop_table('location')
    op.drop_table('data_source')
    # ### end Alembic commands ###